language: node_js
node_js:
    - "10"

# 缓存 node_modules 文件夹，不需要每次都下载安装全部 npm 包。
cache:
    directories:
        - node_modules

# 只对指定的分支执行构建
branches:
    only:
        - master
        - dev

script:
    - npm run test:cover
    - npm run codecov

# 配置当构建失败的时候发送通知 https://docs.travis-ci.com/user/notifications
notifications:
    # 设置 TravisBuddy，每当 Pull Request 构建失败的时候，TravisBuddy 会收到通知
    # 同时会将 构建失败的日志 以评论的形式添加到 Pull Request ，方便 PR 的提交者查看错误原因。
    webhooks:
        urls:
            - https://www.travisbuddy.com/
        on_success: never # 构建成功不发送邮件。默认是 change，即默认只有上次失败这次修复的成功构建才会发送邮件
        on_failure: always # 构建失败总是发送邮件。默认就是 always
